### ISSUE TITLE
Looks like the content of the sample_db.json does not match the model?

### ISSUE THREAD

**Issue by bmalnersic** [esmaily/python-soap-server#1]
Hi,
It looks like the sample_db.json does not match the schema and model and therefore example SOAP requests will fail. e.g. sample_db.json has uid keys and schema defines id keys. Or am I doing something wrong?
Kind regards,
    Blaz

**Comment by esmaily** [comment]
Hi 
yes sample db is not match with code . 
Thanks @bmalnersic

**Comment by esmaily** [comment]
Hi 
yes sample db is not match with code . 
Thanks @bmalnersic

**Comment by esmaily** [comment]
this issue fixed.
